org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=unmount
mod_name=Unmount
mod_license=MIT
mod_version=1.0.5.1
mod_group_id=io.github.derec4
mod_authors=DerexXD
mod_description=Automatically break minecarts and stop collision bounce-back.
